{{- range .Values.loggers }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logger-{{ .id }}
  labels:
    app: logger-group
spec:
  replicas: 1
  serviceName: logger-{{ .id }}
  selector:
    matchLabels:
      app: logger-{{ .id }}
  template:
    metadata:
      labels:
        app: logger-{{ .id }}
    spec:
      containers:
      - name: logger
        image: {{ $.Values.image }}
        imagePullPolicy: Always
        env:
        - name: ID
          value: "{{ .id }}"
        - name: LOGS_PER_SECOND
          value: "{{ $.Values.logsPerSecond }}"
        - name: ALLOY_URL
          value: "{{ $.Values.alloy.url }}"
        - name: ALLOY_LOGS_PORT
          value: "{{ $.Values.alloy.logs_port }}"
        resources:
          requests:
            memory: "24Mi"
            cpu: "10m"
          limits:
            memory: "48Mi"
            cpu: "25m"
---
{{- end }}
